WMO:
  0: "Clear"
  1: "Mostly Clear"
  2: "Partly Cloudy"
  3: "Overcast"
  45: "Fog"
  48: "Rime Fog"
  51: "Light Drizzle"
  53: "Moderate Drizzle"
  55: "Dense Drizzle"
  56: "Light Freezing Drizzle"
  57: "Dense Freezing Drizzle"
  61: "Light Rain"
  63: "Moderate Rain"
  65: "Heavy Rain"
  66: "Light Freezing Rain"
  67: "Heavy Freezing Rain"
  71: "Light Snow"
  73: "Moderate Snow"
  75: "Heavy Snow"
  77: "Snow Grains"
  80: "Light Showers"
  81: "Moderate Showers"
  82: "Violent Showers"
  85: "Light Snow Showers"
  86: "Heavy Snow Showers"
  95: "Light Thunderstorm"
  96: "Thunderstorm + Hail"
  99: "Severe Thunderstorm + Hail"

ICONS:
  0: "sun"
  1: "sun-dim"
  2: "cloud-sun"
  3: "cloud"
  45: "mist"
  48: "thermometer-snowflake"
  51: "cloud-drizzle"
  53: "cloud-drizzle"
  55: "cloud-drizzle"
  56: "thermometer-snowflake"
  57: "thermometer-snowflake"
  61: "cloud-rain"
  63: "cloud-rain"
  65: "cloud-rain"
  66: "cloud-snow"
  67: "cloud-snow"
  71: "cloud-snow"
  73: "cloud-snow"
  75: "cloud-snow"
  77: "snowflake"
  80: "cloud-rain"
  81: "cloud-rain"
  82: "cloud-rain"
  85: "cloud-snow"
  86: "cloud-snow"
  95: "cloud-lightning"
  96: "cloud-lightning"
  99: "cloud-lightning"

STATE_CODES:
  "ALABAMA": "AL"
  "ALASKA": "AK"
  "ARIZONA": "AZ"
  "ARKANSAS": "AR"
  "CALIFORNIA": "CA"
  "COLORADO": "CO"
  "CONNECTICUT": "CT"
  "DELAWARE": "DE"
  "FLORIDA": "FL"
  "GEORGIA": "GA"
  "HAWAII": "HI"
  "IDAHO": "ID"
  "ILLINOIS": "IL"
  "INDIANA": "IN"
  "IOWA": "IA"
  "KANSAS": "KS"
  "KENTUCKY": "KY"
  "LOUISIANA": "LA"
  "MAINE": "ME"
  "MARYLAND": "MD"
  "MASSACHUSETTS": "MA"
  "MICHIGAN": "MI"
  "MINNESOTA": "MN"
  "MISSISSIPPI": "MS"
  "MISSOURI": "MO"
  "MONTANA": "MT"
  "NEBRASKA": "NE"
  "NEVADA": "NV"
  "NEW HAMPSHIRE": "NH"
  "NEW JERSEY": "NJ"
  "NEW MEXICO": "NM"
  "NEW YORK": "NY"
  "NORTH CAROLINA": "NC"
  "NORTH DAKOTA": "ND"
  "OHIO": "OH"
  "OKLAHOMA": "OK"
  "OREGON": "OR"
  "PENNSYLVANIA": "PA"
  "RHODE ISLAND": "RI"
  "SOUTH CAROLINA": "SC"
  "SOUTH DAKOTA": "SD"
  "TENNESSEE": "TN"
  "TEXAS": "TX"
  "UTAH": "UT"
  "VERMONT": "VT"
  "VIRGINIA": "VA"
  "WASHINGTON": "WA"
  "WEST VIRGINIA": "WV"
  "WISCONSIN": "WI"
  "WYOMING": "WY"
  "DISTRICT OF COLUMBIA": "DC"